### ISSUE TITLE
ptvsd never return.

### ISSUE THREAD

**Issue by dongwangdw** [hyperledger/aries-cloudagent-python#70] opened 2019-07-14 03:49 UTC
I try to run the local daemon with `./script/run_docker`. 
The script is stuck at `=== Waiting for debugger to attach ===`.

I doubt it is expected. Just want to confirm this. Or I missed anything.
I have installed the ptvsd module.

**Comment by swcurran** [comment] 2019-07-15 21:27
@nrempel - can you please take a look at this?  Thanks!

**Comment by nrempel** [comment] 2019-07-15 21:48
Hi @dongwangdw, this is intended behaviour if you pass the `--debug` flag when running the agent. If you do not use `--debug`, you should not see this.

**Comment by dongwangdw** [comment] 2019-07-15 23:40
Yes, I run the command with `--debug`.  OK, if it is expected, shall we just make it clear on the doc and tell people what is this and what to do with it.

**Comment by swcurran** [comment] 2019-07-16 00:11
I think the question is more whether the `run_docker` script should be using debug mode by default.

@dongwangdw - I assume since you mentioned ptvsd you are aware of what it is, and you know about the various command line parameters - listed here: https://github.com/hyperledger/aries-cloudagent-python/blob/master/DevReadMe.md#command-line-arguments (--debug means `Enables a remote debugging service that can be accessed using ptvsd. The framework will wait for the debugger to connect at start-up.`).  ptvsd is described here: https://github.com/Microsoft/ptvsd

**Comment by swcurran** [comment] 2019-07-16 00:21
Hmmm... run_docker doesn't do --debug by default, so all good.

**Comment by dongwangdw** [comment] 2019-07-16 01:21
@swcurran thanks for the info.
I just want to run through the startup. So that does mean I would need to config the debugger connection before I run the command ,right?
The command I ran is `./scripts/run_docker --inbound-transport http 0.0.0.0 10000 --outbound-transport http --debug --log-level DEBUG` from [here](https://github.com/hyperledger/aries-cloudagent-python/blob/master/DevReadMe.md#running-locally)

**Comment by nrempel** [comment] 2019-07-17 17:56
Hi @dongwangdw, you can run `./scripts/run_docker --inbound-transport http 0.0.0.0 10000 --outbound-transport http --log-level DEBUG` which omits the `--debug` flag. This will run the framework without waiting for a debugger to connect.

**Comment by dongwangdw** [comment] 2019-07-18 00:23
@nrempel OK. I will run that again, any issue I will let you know.

**Comment by nrempel** [comment] 2019-07-23 17:03
@dongwangdw I'm closing this for now, but please open a new issue if you have any further problems.

**Closed by nrempel** 2019-07-23 17:03 UTC
Labels: question
