### ISSUE TITLE
Proof-Request is successful when presenting credential from different ledger, but "same" issuer DID and schema

### ISSUE THREAD

**Issue by esune** [hyperledger/aries-cloudagent-python#544] opened 2020-06-04 23:16 UTC
### How to reproduce

**Given:**
- **LedgerA** and **LedgerB**
- **IssuerA** registered on **LedgerA**
- **IssuerB** registered on **LedgerB**
- **IssuerA** and **IssuerB** possess the same DID (e.g.: same issuer entity on two different Ledgers)
- **IssuerA** and **IssuerB** issue credentials tied to a schema with the same **schema_name**, **schema_version** and attributes

**When:**
- A credential is issued by **IssuerA** on **LedgerA**
- A proof-request is initiated by an agent registered on **LedgerB**
- The proof-request applies attribute restrictions using **issuer_did**, **schema_name**, **schema_version** requesting a credential issued by **IssuerB**
- The credential issued by **IssuerA** is presented instead

**Expected result:**
The proof-request is not satisfied.

**Actual result:**
The proof request is satisfied.

----

This behaviour was observed when responding to a proof-request initiated by a verifier ([vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc)) registered on BCovrin Test Ledger and using a credential issued by an agent registered on Sovrin StagingNet Ledger.

The same issuer (DID) was registered as endorser on BCovrin Test first and then was pointed to Sovrin Staging. The wallet was NOT cleared when switching ledgers (I don't think this is required) so that the agent could be pointed back to BCovrin if necessary.

Below are two of the cred_def transactions involved in the proof request being performed when the behaviour was observed (multiple credentials are involved in the original proof request).

Credential definition transaction on Sovrin StagingNet:
```
{
    "auditPath": [
      "49kKnNFonyeqbtB27kkYr46au656zD6BTyfjJ987qyKs",
      "3xGzE33Bd4CPftS9eMpSG3udiYYwMbM1DCjg5cwdhRux",
      "5KSfRFrnXjh7E4rPHd8ezVDPF8GsdnKnxrbCVc9Fuwbc",
      "CNwX3eoPh5bb6jKrF6ZA16ezJnd2gSK4mFBMJ6iNpkRW",
      "Hf1CrLsyzVxARYZZTPeApH3rx8p2MqQ4q36oeBqeXutH",
      "6FK38Hdajy4HoS8KZXFgxEHUv5GwqZTj2TM3AfYYYRvh",
      "EzmfeCm99p8cHuzB6LHLQcu8B1wspQrdJURAb6jHb6XC",
      "3s8uGqB24qAsEn8QsrL5KbKvGyuG9L7qb9sbboyxSott",
      "9E6NTbwd8LYMbSKGT2XFyWX8cvoCa2owhEGCTMfqq6Qg",
      "7r5vhvyN9gFsEadtAXMXeFAt558zUEPv5R7ngX9G945b",
      "CEv4WJQbi4k3wry1ohjuRBkB3yCWCVe8cJhk4LbU1m7c",
      "HKjeaBHCVdccqiikj5YE8hdvhZXCaGBsoHFM7XTjdAge",
      "EmviEJYzYq4UsT7RvR2H8Ypb7mhKMabhz45LWasgERN"
    ],
    "ledgerSize": 106456,
    "reqSignature": {
      "type": "ED25519",
      "values": [
        {
          "from": "NCwGwDrzbZEqesYQummzWW",
          "value": "4tGjuPPLmCNwVTc1G53Dyfdz7vmJAC3NuXjsJf4VU7cAksgKkTPt2A3SzoUBpamXiNQkUwYTABSRGVCYbZYNvSW2"
        }
      ]
    },
    "rootHash": "9iwX4ZA1NRqqmjQmE8Kte9F68CRofgrqifs57upaerRC",
    "txn": {
      "data": {
        "data": {
          "primary": {
            "n": "84837249107050869332646904083434985534477272658332311661154298206839429730135348582042926191612821810263713689352485736231760760779063530938421660089422948553056660078817021195453125963516085580973302972133404776735270715827453668736401737666901732762922852896079457859688006428245707460073241850198971836010978077124952057525822374129116154242111904284736912315551801796106225134800428029889596434254237607242578728089831863123656672022082185175583810965390460036068341231612517227914586454356863459060173215872620766808201680370891060216748619411694434472284727633832476272875253265086699274836389772185942359467941",
            "r": {
              "birthdate": "31576642245434551207596724297333592158928580786103254233570374446782249576201725216585099132968752383278158613202036892582331864357384185547614015148228678320895963165856685670498200400469525478602369064306179493989682135620454249195693501437066104807676620605096239728455489829180807596726407997574588411853047743618840576580804390808186025368905182075358444988191945719600349338141398173095835595486247723992257016983593332952576713063013249059005746131407430345007331587002363502731955057031100245096622742474234974918494028202811168648236629713655125696851922233849752148748963671539972487978907337455913910407065",
              "country": "23759324757254977424842705455550810351911872467813056967048017179676424178205066711807737509254637351093352294715776469741546498278767251442191776747397426290605696306932863288741770908119146452751240707700577025741304278259510373611169407544405284873437648682606587343168624919760527571582579844891985973042146494227555172798000924856146472388174511319039775671365732251571833559553183416939252727795825619257698753459316287071769244293452172332420101569250634109688411937025491462602092706376035724109526876525926617716980216895784375018997603936968503214407255783887755335738030049148799719491110356084816896386435",
              "family_name": "22760329078292803231049794480898633268133957961269349052591234330133114543730954143557280929731150871122658836633759122835116975789532487968966779002807734300191414396615259985358661046291942147370337097282511183766168803091237564841010284630367654575299044180415348830923591530208284333668287905482085571114760172301505949408037118994333348054560907368586943826760565125401457225626901306209129996199786173386061602403985660459822861216025730613415782707223194294220988045134279538808921592798283682910814525561813660387127867681503462771278931385791374719480066517928788486613962316953201632315126795261267963148735",
              "given_names": "84517535608627059711577015998065290829167073293805187609395419007653324204201617886536983950477516332492146748913276343087665353296947875716552596927752516289364916160792861201037787226147670453022359408374332036727425342562671025734439241734123311279909843612905388590040837546486493134403605527672128016337681299733566025408565127633878628045053639150210105848376961810482854664132766601504424353342744774342818502856458785129927287372865908095864972308610052084234622378038841435893095863411418094168825259199461146436434619690316504171158672210277763372367835288436065745564119780134568582836283640512615599597157",
              "issued": "78421386902525610885700783737032551380987215471122617034533360459873720589176765140023094826165338514108336014994057115074379183493837753611413729061560271396821527574236520517680950437404531119346119721824961912159087502150014477885009279452154283803918630304227321711690518023910163388195632720600214114541628865178995668087350012917058111450490806142184022603622217933603819809913982669057357367341673356829022857626318177040083046323022371027165469676775039532520159819271887249959303786954661855979630718038218761570168591489622352462061655582463046890937943188070273348301196685470916065618338690139177958920001",
              "locality": "50512625679302733627916481266068861002985243690345065594388635827309724508459435749464222179285421802500945703741194937111611845930241786463911527714894651948201715498875148689963085993841440122386268331941388273981999597752450223014853481303606147312376491745931081806872725747340104824223922072549681525018232508293859484054013682475061808976157698066482809686448631071323732235081386959944282367419820175588689446467285030530465958101610036434293407599030112248358187803426665425760040612826890865590504997691385008677500949162779461231774897144877631823955929761656470286461064360003834416671822243630152191459896",
              "master_secret": "75029213169021679657745829855638445571246040361685987739072240862646900564885067594620317203924866265299763756481678797567875580181648380224028789967735593384680876742495362078219431033792777079381794464304557470628606079732739343397334423118478675960076367035074310308993872052172086341036915514887515287663943940230778152697611097236900725350759796166299956853394487603044151451351449656513970263774340828165859001338489788385964444872869768631789412861347807985109635474047346507892340877464619363497619264803939907626305278015872547133431210770509455274827310501542274783349399158044148579221182094171971906297268",
              "postal_code": "25455319805893177719728098197899834831282578999270240455443254219575133933418430126502079074275424734227843062949146199033659942976208567468324173020361378635097262808858023984937677612643124698297980746027051500078009498114463810776563739101738143218915286019394935412138400418518489095492146307730178409302691745078761858353332029090869005206508384360454247230116928995501593495754022095024598373443981794882665055744118288228675816449665160850485416998847692379048106185022576217455393706105894308742928667465964678627622184294312751604987221577414458030416042158278050511328480841465405241310558216972221440986859",
              "region": "53332235300916124033194128822269050595962866579698502227453771255787648524824451957508951175976873342332846516355558983560759454135053244667625421479115731368858421807524309074149831356104112384337432786036925833480742096215490847211707210970077067353920090081507471731006354751726448486935065930878018115444020536279963100449773613591605583893001130166157026428558239416992840732848197515052097080595832319570898333252869358894564574625907629671401477211350490307185103104418089249018536919270082108142095931574186346490092655028506617350697271469577175319025640763256595969971316919703099344729612451184612555121677",
              "street_address": "19681872631273563387685099045260834353746891501818661532639933856500009719649916905940575120230994008557219857063947894666402606134002065854873869556274078708887226536888195660194066758117445263903634623117117141850698584377314237737557306859153746509877716953290212511483128650189457994261698124438722470237113289235654574783584921244539638101398955175817735650523384167182366831397564440352544297906588002461773278556192515280036274173831351225518813687271183326055033601433181249355611023751719295568365295267283504180729733277311691616679051690757006127616973653096024237668748302776795784684805864465384592323937"
            },
            "rctxt": "20710225477178671599160301714822254447660892406945725754844181225293145891063082473271937543233291113432180852115355543493604608724066018280020278725448832239343175658400996988903180680354088057816589804540497717058456910192113219446032135684920893225887064578758036072463018377755095255509804599951466815747835396927258542242003162283576628263241486049098733676209177197101970356520222887385183562706088569393335073282574059213413230057967282722488927725566810185029511284677868170677314721281357410687941890156350188549978285756295728281130984578142575710548526505844311074736187669522476582449897269617507532003866",
            "s": "13719170099024357804103983640369505955284451426037747013607348923752576483139254499941044216565362309220024854808934095058484408962724298281126095385184132201683820430605624856464833272426980262961872837948731763722331006769547418448600058065929164883141404785394032643666405650388116717453500286114570962985623055349733716999864212895315864414540160994164117801757553514348299364898877466025694538606712309483158221658876199510362270265666147248768376756200752132597150810962049907845299371569170587997251570126623181269374049927870263041797959210973607470558762851865710700103052104657145386672135720802966324709511",
            "z": "35912842737381933626548107077310123760016340641694177934602699049419934526998623602043713231742756950805735402086453437215155869062277121435960813478647706666308787137247134030523044202420482762900363767049670004187495231268638210017426998189352593519196054914698391965925690426876457447204936423078544505647679151248915412193005124420255101072464444910581646052430981960024077772584981024748945819454599737574261667456324121482330320063579828660866976243023831467140133913770955874962628413771294109934356615176058506433579212529870642055647152980500643319505304638290920758763849337502173969802490328166245157129854"
          }
        },
        "ref": 106455,
        "signature_type": "CL",
        "tag": "default"
      },
      "metadata": {
        "digest": "9e236fc2297f64b49327ea935ddf0ecdfcf908fd1a7f74c1c7d5b6357be87e2b",
        "from": "NCwGwDrzbZEqesYQummzWW",
        "payloadDigest": "6052b3de41ec1b66485e1d74ceb266b90d2bb37cb728799b9038188eb4278bd3",
        "reqId": 1591299911239918800,
        "taaAcceptance": {
          "mechanism": "at_submission",
          "taaDigest": "8cee5d7a573e4893b08ff53a0761a22a1607df3b3fcd7e75b98696c92879641f",
          "time": 1591228800
        }
      },
      "protocolVersion": 2,
      "type": "102"
    },
    "txnMetadata": {
      "seqNo": 106456,
      "txnId": "NCwGwDrzbZEqesYQummzWW:3:CL:106455:default",
      "txnTime": 1591299911
    },
    "ver": "1"
  }
```

Credential definition transaction on BCovrin Test:
```
{
  "auditPath": [
    "6o5WRxrNmuxEEJU673bGYTSecqjck2RVwtRWecJMHMFS",
    "EyBU23nWd3mGirpX6SuHfrp256geMws9DHDAYV42FSVk",
    "9hG29kpB5iKboiw4stugtLqWWGEVwPw88JAN17KMpVoQ",
    "7pXgb3BX2VBENZ2ZgPT9k6J3CuiEuQzfXsjTxCcMdvqd",
    "dWeTNduqcF3biMwztEBuBGTa9tEdnDPXMJjCYa7br1J",
    "FfqnZKmxCR8nnb5YXRU9v8iedF6CqxrwixgXnXuNNEhA",
    "5PVSHYjbxo5vxJp5wvEqStz6A3UcFs1o1Yrd35dkisPK",
    "4nGTv6dxesWvhmLSR3pxaB38n5yTruvfk6hqmTsjVbBo",
    "7HB99cCfDDPG92hd3MgmMprPXPrxRvB76rP2j51DJ5Nf",
    "Eyu1zU444Epqi6igbWWUaJfX1N7h28H9eW4j6E6zhxC4",
    "GuhGdoBiAtG8jJMVc637WtBXsfzpWEq9P7AFgMtWNHMU",
    "4itr5pvm8EVUST7zr2741BoEo7PTzLz84DdYg7YGmxmK",
    "DEoob9SQpepKRqtg227fynMkDuM4Dbe4PLEAkfU9zDwm",
    "D5YYzms1bB7sztpb2Aqcyp7hEzrf2Mf7hPJ4t8yShDyV",
    "21XSrk5TNcTx6QcotdunqbGn1w4LBxXpAMCzEpRtXMS6"
  ],
  "ledgerSize": 20211,
  "reqSignature": {
    "type": "ED25519",
    "values": [
      {
        "from": "NCwGwDrzbZEqesYQummzWW",
        "value": "Sg5uQcaefy1shGD2BbpscdaKThAKL3UhhfP5QF32ZCJUNDDRvd3WtKdmy5M7uoVpj7bnPAmiUJ8EpxNeZPQ1pSQ"
      }
    ]
  },
  "rootHash": "9QMD3Byh7xt8KSGK1SiiMNbt56Ph6AeBCA8Lxdf3yKAS",
  "txn": {
    "data": {
      "data": {
        "primary": {
          "n": "96021139521104697823715221736964427753642716964155581577431249078728749847094816399525890570474738428709712328750574830049376597395026847797152582824234539215273690992996780815685895179859484808449153634459868651736816075337332861001025839455406726241100988707893048724704202890572730513846123326513893341762477667242389691964988051289674065551271724907156073035844782408983896190586130846280829933273793530972308766946524417673693613186408136507690063943421466121273355809579575289194224340850850031950561316813124853738001308867021402053998282984184927540031393391672200177343952032951148359203292749317097188489433",
          "r": {
            "birthdate": "24673401369063384274644645734486339834648002316630522887450439181697755626161275175224712125337518773792916558592244121591798969824367650824057221422213348429415979783703531887056147574217751073822478335345302870566662109369719325769526276546941637682594918793068113252870568330207661091760685558284817732396138739243781156946429609798510755114968033837540974199247364771179370161348789607549177484075573883393535881240832892704461474939308394990765476607103067172221123330757491353272593435898104429330026144097454405525246665445086070222678797606388720119683492866651339610415621879352853144194972098856925657845780",
            "country": "58007276651341834927726388302557643686363772047834864339719442869379206866912353004201431039113313965248847504342881353342307686370904288997756215530596351259792917111952594182315870511986692052229417851592345660414041721619647793315312525958621197576167554455315656650275059348228956348322696565387018279550078215606766976022751972241130587580812865628432776167288082513682608951912665674635782176704387994608465667620748276987884429655935459305692645437829019571062220881546606740282576880380889045235742747613412511667540234140275472875854195333092009570985287134062717424758411233113348310588512087886865130783856",
            "family_name": "3562197825627801184313796358523663535321474030362675014706549068841086611825820408832443117789480539627904146340309078775260873752614529669044962597497755769108022134698455318752381039422739997178740643155835653126052524506907134315157972645435452499455676515086453203649102509551018476276043185321521696515696539902781315920415605458093537342333179768112336939814170826870829863246824554897056042225271780585949285398983006565025853711061850403455524146940732223130314321196565083054471199328015010843960009262143287672715967404974073221973567447248525314203419922047535099765671922002495718191722124121029419350717",
            "given_names": "77099951443349918991203776944456045455182819779099236351056171695316693113336599442635075156536322511105672680529699081761775829992518087042085234647731497153746426081906635425294366995405982994490934862806027787813978720225834242542668463690797940673343563261794720632672067742594689005880192363505488009615898431231109106118055760678858112220371054522281721151468038833189538122291536290937040251810788541914902725421842000628323225958678919634591462646913123547399932915533381854419929192322700344898451736996129253089009684079369829363766298389731607782868923676916676679848527701619150226557149304419408099589953",
            "issued": "82905291955592375679767526124010064586143838712270503189369881812966149266315089741106851452928829372002485869193912433953421826270206491496225102495716335197431121819588794799623327766913691856770899239380401032088619324339279494634919236695761479760293956986652873121287176638779708641827579321385203120179807001950737689370994249394433746144810765177999376894755120755678481333613931875461575600517378921532716458979969611384024389356020498045880052169731742002162092595349005092773750308616168803418793051637096078730738474391590502088164604165645500529535489886442531730189273015955309998679841610634688681927455",
            "locality": "27411425286515794138711169273148749116807668799056751571392146045777235727426714299090299734027795775768236403220927415773175170035037579379049806924333992925978991717211587348881056354394906055911504749411662840475780589587463895761530293536874139954450243707934953401359454611720027358042695556632190311176933964760776319216051270462072918024536554582712931285434979513299116896443948117852175442981521265955952444009914898315937672430061347372516990304768843523323112446318087710589176052458805382669512346770796493209705509951359568736505814605670865499789320652170030867055058894020141644910964872574905067387690",
            "master_secret": "34715841155083304567839082341397344689726622048046263582780213805037026478656078120731738911579171624543298017758192189265616610800765056381470256061592839126549553932475450433010541766792543530815077549428084341437813338012422743430750554152573603600224301419942632811743370101133517281015735891721738321400714652997660303262623589158827742871722144239635659801148500112289113405870632963412177230741190490007354729521562183951225184114678039302613016397865492865262410265118584591986947539434591344869270668949601412336133546751304341453112882884735191989774167071770938947149675042445880115876314153135162241290632",
            "postal_code": "78331461338893838250273360282607775957347238135988314627782017744620604947262649801036809638289852240438361331331303269976964330587237299631372629170323260436554840910446720358345439685514826771911498180390262706131017438682105144620029232072653061679062978226034306841785748965086382115384604896564976234815905958365073702394356980826346735258106964732947455743881664661767322752625896943776065140164828882828816868481230633535252117355255936869455505922823074474913445185657404173493008092615897087175207683214696732028242750481833806177106848221261342047655290779716934107046543787964004031385848447656987518666554",
            "region": "54435657817764567284961894779514018699509401725349282320617328920190243339901115323528560351109015162105586932075271073217687882091288606192110343087709133048740434017830770471790216160968169096264951321980020058041084772148144777172253737858451695205343858639891540328029486868320396379544895937113474324358318890293281695431343214202482885433724941331933204063484225680107103742810924269544716022426530960112104042132556995081908439038449391137581871260432124269047976462884122466955523118202555198200878707541614459657097452575035157906347844438342558843964618369130758341858242934270816327948079291755610895224456",
            "street_address": "36939708725758078167576657409586345719396089234183067015843252471979016046652899062002895092560043899513745012853740097674468601748740086944418998799702983304242040931959791792770441898353145665169178577346759484260081275218563433231148002488422814757601978437568602216285085272653735240464561232523943089225469542892268110594842797586224618850654115049217716352489359645450488207014694556424071405693588249457414660347233807942436110036724297615440609176323193999449790109117475073916098782938404076723494127470576937992436919331834709951408729883589523245921221896175863833546380797919061680482812786855223169367086"
          },
          "rctxt": "78598972728554353469240273361218392587777321315188908252664988680340239587945916445712189705884526026982658146803275440322066925905055694881222185249642915270236225144848660819590331406083321516882757396025004104987990008840153700588189630717010500553577338065497618986443265883793305323181226109957133569431655441274149396953612990616219266720371616500730626703877893845477697473324299449117911816079558331327572070077922767391659536041395231908104200129309598753728326937123071500730612682206493875472252449715139900287277295372215453566515081192735559916418542172645087012925594658868925400506825129339097077257038",
          "s": "34422335365863213471969350920076501520127750460260594461771612232548195562859595640929392565623433313608015347596077500667735296751515123410855562520535890973712940846747452446695610196512614021865654595100427690872088356333726574154111007687227775494068128308863677676121586633792888215236469011802621379418117442232566942663477487366551833951329602698050575647719660887734819162311434176171856328381742394806223343738558666331177713243408971950394897134748590047815018654544539754751736662705533294572521202491137044851096550466470345533286356836342681185692602941971939547501231371136805953908841328606480345950553",
          "z": "23253433847462323260255665936439181097360214561405008156726988871032135604575374684985259792714855160975668146012696396954392778354097407762587944359363370673157262727031971519912567201713099931234435778737088440847879537363619287017307447650565552425795104348188482882596639291129370020418524585396589859647741242755252446654574462804108761934718635043151220017336545319917188111621245502978967959262416897293869690595846150896157042086580150453982301328957828818959576006317566502473301051633604770036807183586939435598324176766535682772410889165827900990716671398790896013056936104075356861432922656773828851609126"
        }
      },
      "ref": 4867,
      "signature_type": "CL",
      "tag": "default"
    },
    "metadata": {
      "digest": "a5ba2e1beaf4d343da2a1dd320b64177478d706b754ae06d27691ebcdd360a9d",
      "from": "NCwGwDrzbZEqesYQummzWW",
      "payloadDigest": "ac07b414d59c66b9cb8bb514434f402e64f08505a6cd8f130bf02865791161e2",
      "reqId": 1586996078546009300
    },
    "protocolVersion": 2,
    "type": "102"
  },
  "txnMetadata": {
    "seqNo": 11538,
    "txnId": "NCwGwDrzbZEqesYQummzWW:3:CL:4867:default",
    "txnTime": 1586996078
  },
  "ver": "1"
}
```

**Comment by sklump** [comment] 2020-06-05 02:01
If corresponding issuers used the same seed to generate DIDs then their key pairs will be the same in the wallet. Recommend rotating public DID key pairs with random seeds (I.e. via Admin API) and trying again?

**Comment by swcurran** [comment] 2020-06-05 15:35
I think it is current expected behaviour, perhaps deserving a note. Until the larger issue of being able to recognize multiple ledgers, this could continue.  An agent has no concept of multiple ledgers - just "the ledger".  Thus, it assumes when it needs an object off the ledger, and it already has it in it's wallet, there is no need to go to the ledger.  Since in this case, the identifier of the cred def is the same on the new net as it was on the old, there is no need to fetch it from the ledger; the wallet version should be fine.  Ledgers are immutable, right?

It's also an odd situation in that we are using the same DID on multiple networks.  Is that something that should be done?

Here's what I think is going on:

- Verifier agent operates on first ledger, and in the course of verifying proofs, retrieves some objects from ledger A and stores them in its wallet.
- Issuer agent is attached to ledger B, uses same DID as before and creates schema and cred def. Since the same DID is used the same object IDs (DID, schema, cred def) result.  The object IDs do not contain any reference to the ledger on which they exist.
- Verifier agent is attached to ledger B.
- A presentation is given to the verifier containing the IDs of the objects necessary to verify the credential. The credential was issued from ledger A.
- The verifier sees that the object IDs are the same as what it has in the wallet, uses them and the presentations verify.

What should not work:

- A credential issued by the issuer using ledger B should not be verifiable by the Verifier.
- If the Verifiers wallet is removed and reloaded while attached to ledger B. Credentials issued by the issuer attached to ledger A should not be verifier.

**Comment by esune** [comment] 2020-06-05 16:29
> It's also an odd situation in that we are using the same DID on multiple networks. Is that something that should be done?

I don't see it as odd. Unless I am missing something, I actually think it may become common that the same organization will use the same DID on multiple ledgers in order to be more recognizable (a bit like having multiple web domains with the same name, on different top-level domains.


>     * The verifier sees that the object IDs are the same as what it has in the wallet, uses them and the presentations verify.

As discussed offline - if I understood correctly - the verifier should not be caching information when processing a proof. To further clarify: in the use case that "uncovered" this, the verifier was registered on the "first" ledger where the issuer was initially registered and was presented a credential that was issued on a different ledger.


> if the proof request specifies a cred def id

The proof request - in this case - does not specify a **cred_def_id**, but rather the humanly-readable combination of _issuer_did_, _schema_name_ and _schema_version._



> Issuer wallets should correspond to exactly one ledger

@sklump can you please elaborate on this? I would expect that - using the same wallet instance - when registering the agent on two separate ledgers things would work without having to clear/recreate the wallet. If that is not the case and we do NOT want to support this behaviour for some reason we should maybe have the agent fail when trying to start on a different ledger using an existing wallet (I would think/prefer it just worked, but I am not familiar with the internal agent<->wallet wirings and nuances).

**Comment by swcurran** [comment] 2022-01-11 20:27
Closing this issue.  We have partially addressed this in the Indy Multi-Ledger feature recently added to ACA-Py. Further, we'll deal with this properly with the Indy DID Method.

**Closed by swcurran** 2022-01-11 20:27 UTC
