### ISSUE TITLE
JSON-ld contexts are not handled correctly

### ISSUE THREAD

**Issue by acuderman** [hyperledger/aries-cloudagent-python#1568] opened 2021-12-20 10:57 UTC
While issuing JSON-LD credentials we have come up with an issue which I also replicated in the [demo](https://github.com/acuderman/aries-cloudagent-python/pull/4):

- If the credential has been issued for the specific type, all of the following requests can use It, independently of the context. In the demo, this is [the second credential](https://github.com/acuderman/aries-cloudagent-python/pull/4/files#diff-4483fbdd64e5a2b502ece2d4c01bbdea683025c1d0eaa9b34146738a2fd16b66R199), where the [passport context](https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3) does not include ˙Driving license` type, but the credential is still issued without any errors.
- Sometimes only credentials for one context can be issued. Example
  - Issue credential with `https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2` context -> OK
  - Issue credential with `https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/2` context -> Fails with all attributes dropped error.
 I can not reproduce the second issue with the demo, but the first one can be reproduced and might be connected.

### Reproduction steps
- Clone changes in the [PR](https://github.com/acuderman/aries-cloudagent-python/pull/4)
- Run demo agents:
```
./run_demo faber --did-exchange --cred-type json-ld --wallet-type askar
./run_demo alice --wallet-type askar
```
- Select the issue credential option 2 times (Faber)
- Call fetch w3c credentials endpoint (Alice agent - POST /credentials/w3c)

### Result
- POST /credentials/w3c returns the following result. I left the comments on what is expected.
```
{
  "results": [
    {
      "contexts": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/bbs/v1",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2"
      ],
      "expanded_types": [
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2#Driving%20license",
        "https://www.w3.org/2018/credentials#VerifiableCredential"
      ],
      "schema_ids": [],
      "issuer_id": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
      "subject_ids": [
        "did:key:zUC7Lfm5UEUrZxf6CEeLF7WKbqoJD2gBTMeK8oHAYaZmaTG8HUyoV4UW9ZxzFwA9qDBLBc5uXebUtLMCAdYiSrLrK7hvm9pgcXKXV81S7diGYPxjtwHC17jySLLMPfSmTR1RMc7"
      ],
      "proof_types": [
        "BbsBlsSignature2020"
      ],
      "cred_value": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2",
          "https://w3id.org/security/bbs/v1"
        ],
        "id": "https://credential.example.com/residents/1234567890",
        "type": [
          "VerifiableCredential",
          "Driving license"
        ],
        "issuer": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "type": "Driving license",
          "gender_legal": "M",
          "selfie_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "selfie_video": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "date_of_birth": "1990-10-10",
          "document_number": "10",
          "full_name_legal": "Full name",
          "last_name_legal": "Last name",
          "first_name_legal": "First name",
          "document_front_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "document_date_of_issue": "1992-10-10",
          "document_expiration_date": "2023-10-10",
          "document_country_of_issue": "SI",
          "id": "did:key:zUC7Lfm5UEUrZxf6CEeLF7WKbqoJD2gBTMeK8oHAYaZmaTG8HUyoV4UW9ZxzFwA9qDBLBc5uXebUtLMCAdYiSrLrK7hvm9pgcXKXV81S7diGYPxjtwHC17jySLLMPfSmTR1RMc7"
        },
        "proof": {
          "type": "BbsBlsSignature2020",
          "proofPurpose": "assertionMethod",
          "verificationMethod": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp#zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
          "created": "2021-12-20T11:31:09.964294+00:00",
          "proofValue": "t5Efuv0lbNfasMYfvzL0NgTt64w9KTkplOuFX9ZhHKsXc2+A/bnlAfc4joMbCocyXFpi6SElk3ma+2q+NH3vVftopXOlgr6hStfpfSKkzZRMsOXPD2Hg6VqGR5UBmADm5UhMfAGMPwFYPEPpVJmOsQ=="
        }
      },
      "given_id": "https://credential.example.com/residents/1234567890",
      "cred_tags": {},
      "record_id": "aef4da955e5a4c56b1ef45b95426a268"
    },
    {
      "contexts": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/bbs/v1",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3"
      ],
      "expanded_types": [
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2#Driving%20license", # -> credential should not be issued successfully as the Passport context does not have `Driving license` type defined.
        "https://www.w3.org/2018/credentials#VerifiableCredential"
      ],
      "schema_ids": [],
      "issuer_id": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
      "subject_ids": [
        "did:key:zUC7Hk8fzXvLFsicM9GLBrUVHfCPgFiANZ6bewhkJ65AxEQGQmGDFvGP723GfKnQHPnMTpWXQKAJ21cujJQEDtvEcoJYMeWns6qvv7tmP7D2TGxiLVenPqBWWioY3yhihNGK1Nu"
      ],
      "proof_types": [
        "BbsBlsSignature2020"
      ],
      "cred_value": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3",
          "https://w3id.org/security/bbs/v1"
        ],
        "id": "https://credential.example.com/residents/1234567890",
        "type": [
          "VerifiableCredential",
          "Driving license"
        ],
        "issuer": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "type": "Driving license", # -> Should not be issued as the Passport schema does not include "Driving license" type
          "gender_legal": "M",
          "selfie_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "selfie_video": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "date_of_birth": "1990-10-10",
          "document_number": "10",
          "full_name_legal": "Full name",
          "last_name_legal": "Last name",
          "first_name_legal": "First name",
          "document_front_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "document_date_of_issue": "1992-10-10",
          "document_expiration_date": "2023-10-10",
          "document_country_of_issue": "SI",
          "id": "did:key:zUC7Hk8fzXvLFsicM9GLBrUVHfCPgFiANZ6bewhkJ65AxEQGQmGDFvGP723GfKnQHPnMTpWXQKAJ21cujJQEDtvEcoJYMeWns6qvv7tmP7D2TGxiLVenPqBWWioY3yhihNGK1Nu"
        },
        "proof": {
          "type": "BbsBlsSignature2020",
          "proofPurpose": "assertionMethod",
          "verificationMethod": "did:key:zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp#zUC75D9oXEeUcHiixj8BdzgwsjYcaYi7jRGCdMahqUDRtfXSDkDEXRPuUXTeEU9TSJqFFwaS6nNyWEbfRJe7Y8q3LEcVghsviDJHUx8ohLsigc5RKRxXR5uknv1XSSca3SvnPtp",
          "created": "2021-12-20T11:31:15.196076+00:00",
          "proofValue": "qF7iz+dcwCeTbkt8zy2EumByhsEzyMKU9Sa5HdlYThAn8X+VR6+A4YK+FzGv1eupXOLN2d/vRknea2PBsGvHjgDte1VIKQeAWS1hkawvMYUBqZOVI4ZgbNN5SasmSupeDrlyinpKaNqyw18Sfp4uNw=="
        }
      },
      "given_id": "https://credential.example.com/residents/1234567890",
      "cred_tags": {},
      "record_id": "c45663e0d4094ae6b4c2f6a8cb57783c"
    }
  ]
}
```

**Comment by acuderman** [comment] 2021-12-22 08:01
> - Sometimes only credentials for one context can be issued. Example
>   - Issue credential with https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2 context -> OK
>   - Issue credential with https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/2 context -> Fails with all attributes dropped error.
>
> If the order is flipped, then issuing a driving license credential fails with the same error.

The quoted issue can only be reproduced using the contexts with the `@import` statement. If the import is removed, then It works as expected.

**Comment by shaangill025** [comment] 2022-01-05 15:12
I tested with `latest` and can't replicate the issue.
**Steps followed**
- Started 2 agents, `Alice` and `Bob` (`--auto-respond-credential-offer` `--auto-respond-credential-request`) and setup a connection between them
- Alice issues the following credential to Bob and Bob stores it.
`/issue-credential-2.0/send-offer` request body
```
{
    "connection_id": "...conn_id...",
    "filter": {
        "ld_proof": {
            "credential": {
                "@context": [
                    "https://www.w3.org/2018/credentials/v1",
                    "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2",
                    "https://w3id.org/security/bbs/v1"
                ],
                "id": "https://credential.example.com/residents/1234567890",
                "type": [
                    "VerifiableCredential",
                    "Driving license"
                ],
                "issuer": "...Alice DID...",
                "issuanceDate": "2020-01-01T12:00:00Z",
                "credentialSubject": {
                    "type": "Driving license",
                    "gender_legal": "M",
                    "selfie_image": {
                        "type": "File",
                        "url": "https://example.com",
                        "decryption_key": "decryption_key",
                        "media_type": "image/png",
                        "sha_512_sum": "sha_512_sum"
                    },
                    "selfie_video": {
                        "type": "File",
                        "url": "https://example.com",
                        "decryption_key": "decryption_key",
                        "media_type": "image/png",
                        "sha_512_sum": "sha_512_sum"
                    },
                    "date_of_birth": "1990-10-10",
                    "document_number": "10",
                    "full_name_legal": "Full name",
                    "last_name_legal": "Last name",
                    "first_name_legal": "First name",
                    "document_front_image": {
                        "type": "File",
                        "url": "https://example.com",
                        "decryption_key": "decryption_key",
                        "media_type": "image/png",
                        "sha_512_sum": "sha_512_sum"
                    },
                    "document_date_of_issue": "1992-10-10",
                    "document_expiration_date": "2023-10-10",
                    "document_country_of_issue": "SI",
                    "id": "...Bob DID..."
                }
            },
            "options": {
                "proofType": "BbsBlsSignature2020"
            }
        }
    }
}
```
- Alice issues the following credential to Bob and Bob stores it
```
{
    "connection_id": "...conn_id...",
    "filter": {
        "ld_proof": {
            "credential": {
                "@context": [
                    "https://www.w3.org/2018/credentials/v1",
                    "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3",
                    "https://w3id.org/security/bbs/v1"
                ],
                "id": "https://credential.example.com/residents/1234567890",
                "type": [
                    "VerifiableCredential",
                    "Passport"
                ],
                "issuer": "...Alice DID...",
                "issuanceDate": "2020-01-01T12:00:00Z",
                "credentialSubject": {
                    "type": "Passport",
                    "gender_legal": "M",
                    "selfie_image": {
                        "type": "File",
                        "url": "https://example.com",
                        "decryption_key": "decryption_key",
                        "media_type": "image/png",
                        "sha_512_sum": "sha_512_sum"
                    },
                    "selfie_video": {
                        "type": "File",
                        "url": "https://example.com",
                        "decryption_key": "decryption_key",
                        "media_type": "image/png",
                        "sha_512_sum": "sha_512_sum"
                    },
                    "date_of_birth": "1990-10-10",
                    "document_number": "10",
                    "full_name_legal": "Full name",
                    "last_name_legal": "Last name",
                    "first_name_legal": "First name",
                    "document_front_image": {
                        "type": "File",
                        "url": "https://example.com",
                        "decryption_key": "decryption_key",
                        "media_type": "image/png",
                        "sha_512_sum": "sha_512_sum"
                    },
                    "document_date_of_issue": "1992-10-10",
                    "document_expiration_date": "2023-10-10",
                    "document_country_of_issue": "SI",
                    "id": "...Bob DID..."
                }
            },
            "options": {
                "proofType": "BbsBlsSignature2020"
            }
        }
    }
}
```
- Bob fetches stored w3c credentials
`/credentials/w3c`
```
{
  "results": [
    {
      "contexts": [
        "https://w3id.org/security/bbs/v1",
        "https://www.w3.org/2018/credentials/v1",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2"
      ],
      "expanded_types": [
        "https://www.w3.org/2018/credentials#VerifiableCredential",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2#Driving%20license"
      ],
      "schema_ids": [],
      "issuer_id": "did:key:zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq",
      "subject_ids": [
        "did:key:zUC7Fbz2u8vmR5j4yGKSzRFe1TVZyWoB15KyPE3gtZowG7a69iB3K86n71oVDoQUHkpoU8aD44QYgqtaWUPXb7WaNysZegRKf1H41hNTyC14bBEUaRZBwCLqSCxhacsHsnDg6an"
      ],
      "proof_types": [
        "BbsBlsSignature2020"
      ],
      "cred_value": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://ssi.globalid.dev/v1/schema-registry/contexts/Driving%20license/versions/2",
          "https://w3id.org/security/bbs/v1"
        ],
        "id": "https://credential.example.com/residents/1234567890",
        "type": [
          "VerifiableCredential",
          "Driving license"
        ],
        "issuer": "did:key:zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "type": "Driving license",
          "gender_legal": "M",
          "selfie_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "selfie_video": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "date_of_birth": "1990-10-10",
          "document_number": "10",
          "full_name_legal": "Full name",
          "last_name_legal": "Last name",
          "first_name_legal": "First name",
          "document_front_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "document_date_of_issue": "1992-10-10",
          "document_expiration_date": "2023-10-10",
          "document_country_of_issue": "SI",
          "id": "did:key:zUC7Fbz2u8vmR5j4yGKSzRFe1TVZyWoB15KyPE3gtZowG7a69iB3K86n71oVDoQUHkpoU8aD44QYgqtaWUPXb7WaNysZegRKf1H41hNTyC14bBEUaRZBwCLqSCxhacsHsnDg6an"
        },
        "proof": {
          "type": "BbsBlsSignature2020",
          "proofPurpose": "assertionMethod",
          "verificationMethod": "did:key:zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq#zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq",
          "created": "2022-01-04T13:14:19.261889+00:00",
          "proofValue": "hXK2UtHU3Sn9T7ey/o78ubntPS6g8WN0DYyRVGPQlyfgUJGul8UH6DbwIB0HVVh5Wrrbnd5PdZFja8Dl7Y8LZLuwdyY5/3Pcwf7bXqHpgNtqk3UaFSTZA1mHDnHrvXhYJAfuZbICWmUOB2oMoQoolA=="
        }
      },
      "given_id": "https://credential.example.com/residents/1234567890",
      "cred_tags": {},
      "record_id": "ac059ae9e84b4b29a47412f9532fcf29"
    },
    {
      "contexts": [
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3",
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/bbs/v1"
      ],
      "expanded_types": [
        "https://www.w3.org/2018/credentials#VerifiableCredential",
        "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3#Passport"
      ],
      "schema_ids": [],
      "issuer_id": "did:key:zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq",
      "subject_ids": [
        "did:key:zUC7Fbz2u8vmR5j4yGKSzRFe1TVZyWoB15KyPE3gtZowG7a69iB3K86n71oVDoQUHkpoU8aD44QYgqtaWUPXb7WaNysZegRKf1H41hNTyC14bBEUaRZBwCLqSCxhacsHsnDg6an"
      ],
      "proof_types": [
        "BbsBlsSignature2020"
      ],
      "cred_value": {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://ssi.globalid.dev/v1/schema-registry/contexts/Passport/versions/3",
          "https://w3id.org/security/bbs/v1"
        ],
        "id": "https://credential.example.com/residents/1234567890",
        "type": [
          "VerifiableCredential",
          "Passport"
        ],
        "issuer": "did:key:zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "credentialSubject": {
          "type": "Passport",
          "gender_legal": "M",
          "selfie_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "selfie_video": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "date_of_birth": "1990-10-10",
          "document_number": "10",
          "full_name_legal": "Full name",
          "last_name_legal": "Last name",
          "first_name_legal": "First name",
          "document_front_image": {
            "type": "File",
            "url": "https://example.com",
            "decryption_key": "decryption_key",
            "media_type": "image/png",
            "sha_512_sum": "sha_512_sum"
          },
          "document_date_of_issue": "1992-10-10",
          "document_expiration_date": "2023-10-10",
          "document_country_of_issue": "SI",
          "id": "did:key:zUC7Fbz2u8vmR5j4yGKSzRFe1TVZyWoB15KyPE3gtZowG7a69iB3K86n71oVDoQUHkpoU8aD44QYgqtaWUPXb7WaNysZegRKf1H41hNTyC14bBEUaRZBwCLqSCxhacsHsnDg6an"
        },
        "proof": {
          "type": "BbsBlsSignature2020",
          "proofPurpose": "assertionMethod",
          "verificationMethod": "did:key:zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq#zUC7EHPy8YfXxurHyXYAkxJFFKE6o7nPpadHauspcBcC2nkQh9EpHPCKLCcKqJdJa56aamiUH6vxGZapvFiEJ4rGPnUMD69CwiXRiykmbRusFob6fqQB46WBFywgs6oBdCiDFLq",
          "created": "2022-01-04T13:15:46.362073+00:00",
          "proofValue": "qKPNS5JkXTFrUDd3vtOMUtu5G6XPeJ9KkvF7IDJ/Q0WqqwE+YhFJ4J0B00igndIwMjE2Jlpo1gJAaocy1AaGQ2aOz1IAlKXotiVgHcNDE4sDWoxxTovD5rQ7lXy5Vy4I+gSP06B4ncd66iV9ob3GRA=="
        }
      },
      "given_id": "https://credential.example.com/residents/1234567890",
      "cred_tags": {},
      "record_id": "e1ba90d570f24266ba89e97734977f36"
    }
  ]
}
```

**Comment by shaangill025** [comment] 2022-01-06 07:10
@acuderman Can you test with PR #1587, now it shouldn't issue the credential and instead, send a problem report back.

**Comment by acuderman** [comment] 2022-01-06 09:47
@shaangill025 The logic seems to be working ok.

 I would suggest that the type check is also included in the create offer API. [Create offer API already checks for missing context attributes](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py#L405). By adding this the issuer gets feedback at the start of the process, rather than at the end.

**Comment by shaangill025** [comment] 2022-01-06 19:04
> I would suggest that the type check is also included in the create offer API. [Create offer already checks for missing context attributes](https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/issue_credential/v2_0/formats/ld_proof/handler.py#L405). By adding this the issuer gets feedback at the start of the process, rather than at the end.

@acuderman I have made the requested updates.

**Comment by acuderman** [comment] 2022-01-07 07:59
@shaangill025 Thanks! Ran a test. Looks good

**Comment by TimoGlastra** [comment] 2022-01-10 14:54
The issue seems like a problem with the pyld library itself. If you use drivings license context it somehow caches the result and will use that when a type cannot be found.

See this repl.it for a reproduction of the issue separate from ACA-Py: https://replit.com/@TimoGlastra/ContextIssue#main.py

If you uncomment line 18 in main.py and run it again it will work correctly because you use the passport context before the driving license context.

The pyld library is basically unmaintained, but I think we should look to resolve the issue in there.

**Comment by swcurran** [comment] 2022-06-03 21:13
Not sure what to do with this. I'm going to close this per @TimoGlastra 's comment about where this should be fixed. However, I don't have a lot of confidence it will be fixed.

**Closed by swcurran** 2022-06-03 21:13 UTC
