### ISSUE TITLE
Aca-py add persistent queues to inbound and outbound messages

### ISSUE THREAD

**Issue by ianco** [hyperledger/aries-cloudagent-python#804] opened 2020-11-25 01:53 UTC
Update aca-py queues to support persistence:

- should support a pluggable architecture to allow deployers to configure/select their queue implementation of choice
- default should be the existing in-memory queues (or equivalent)

See:

https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/transport/inbound/delivery_queue.py
https://github.com/hyperledger/aries-cloudagent-python/tree/master/aries_cloudagent/transport/queue

**Comment by ianco** [comment] 2020-11-25 01:54
Note that persistent queues are requires for the mediator and multitenancy enhancements that are currently in development, however the scope of this ticket is to implement persistence for the existing inbound and outbound messages.

**Comment by swcurran** [comment] 2022-01-11 20:45
Duplicate of #1513. Closing.

**Closed by swcurran** 2022-01-11 20:45 UTC
Labels: enhancement
