### ISSUE TITLE
demo Faber agent not issuing credentials

### ISSUE THREAD

**Issue by AnasAlamin** [hyperledger/aries-cloudagent-python#1410] opened 2021-09-13 10:52 UTC
i'm trying to issue a credential in Faber agent demo, but it's not issuing even though i established a connection.

**Comment by ianco** [comment] 2021-09-13 13:37
@AnasAlamin can you please provide more details?

**Comment by AnasAlamin** [comment] 2021-09-13 13:43
i'm following the demo provided in the link below,
https://www.youtube.com/watch?v=AomoHvw4lgc

i was able to issue credentials and it was all working great, but for the latest version it stopped issuing credentials.
i tried different mediators, different test genesis files and even different RNMA versions but it's not working.

**Comment by ianco** [comment] 2021-09-13 14:00
Are you testing with BiFold or a different mobile agent?

I haven't tried BiFold but the demo was working recently (last week) with other mobile apps (esatus and trinsic).

**Comment by AnasAlamin** [comment] 2021-09-14 06:45
any news...?

**Comment by swcurran** [comment] 2021-09-14 14:46
Pretty sure the issue is on the Bifold side.  AFAIK, a change occurred there and recent releases (from late last week) were affected.

**Comment by AnasAlamin** [comment] 2021-09-21 11:41
pretty sure something has changed from this side as well.
after your comment i got to make it work with the old version of BiFold, but now i can't even establish a connection neither from the old version of BiFold, nor the latest version

**Comment by swcurran** [comment] 2022-01-12 01:04
Hopefully things have evolved since then. Closing this...please reopen if appropriate.

**Closed by swcurran** 2022-01-12 01:04 UTC
