### ISSUE TITLE
403 No Ledger Available

### ISSUE THREAD

**Issue by Marco77577** [hyperledger/aries-cloudagent-python#1152] opened 2021-05-05 14:02 UTC
I am running a VON network and a single agent in Docker containers. The agent is started with the parameter `--genesis-url http://my-von.network:9000/genesis`.
The genesis file can be accessed via the browser, so the connection should work.

When I'm trying to access the ledger (e.g., create a schema or read a DID/VerKey from the ledger), a `403 No ledger available` is returned.

I googled a lot this afternoon but could not find a solution to this problem. Does anyone know why this is happening, or if I'm missing anything?

If you need any more information, I'm happy to provide it.

**Comment by esune** [comment] 2021-05-06 16:17
First thing to try would be resolving that genesis URL from within you agent container to make sure it is actually addressable.
If you are starting the agent separately from `von-network` chances are that your docker networking is not letting the containers talk to each other.

If however addressing the genesis URL from within the agent continer works fine, please post the commands you use to spin up your agent and `von-network` in order for us to be able to chime in and try and reproduce the error if necessary.

**Comment by swcurran** [comment] 2021-05-09 19:28
Closing -- please open if appropriate.

**Closed by swcurran** 2021-05-09 19:28 UTC

**Comment by santidediego** [comment] 2021-06-02 13:51
I get the same error.

I set up a local network as detailed in the [Indy sdk](https://github.com/hyperledger/indy-sdk#how-to-start-local-nodes-pool-with-docker) repo.

Then I copy the [genesis file](https://github.com/hyperledger/indy-sdk/blob/master/cli/docker_pool_transactions_genesis) from the network and pass it as argument with _--genesis-file_ and debug with _--debug_.

I get:

```
2021-06-02 15:15:58,548 aries_cloudagent.config.ledger INFO Ledger instance not provided
2021-06-02 15:15:58,548 aries_cloudagent.core.conductor WARNING No ledger configured
```

Other interesting parameters might be:

```
inbound-transport:
  - [http, 0.0.0.0, 8030]
  - [ws, 0.0.0.0, 8040]
outbound-transport: http
endpoint: http://0.0.0.0:8030
```

**Comment by esune** [comment] 2021-06-02 15:43
What other arguments are you setting when starting the agent?
Did you already confirm you can address the ledger from within the agent's container?

**Comment by santidediego** [comment] 2021-06-03 07:38
I am passing all of the through a .yaml file:

```
inbound-transport:
  - [http, 0.0.0.0, 8030]
  - [ws, 0.0.0.0, 8040]
outbound-transport: http
endpoint: http://0.0.0.0:8030
admin-insecure-mode: true
admin: [0.0.0.0, 8080]
no-ledger: false
genesis-file: genesis.txn
auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-store-credential: true
auto-verify-presentation: true
debug: true
log-level: DEBUG
```
I am not running the agent in a docker container, rather than in my physical computer using a python environment, so the network should be accessible because it is running in docker in the same machine

**Comment by esune** [comment] 2021-06-03 16:03
I suspect your agent can't actually talk to the nodes in the docker network - I have never used the ledger as per Indy SDK repo though.
Can you try running [von-network](https://github.com/bcgov/von-network) instead, and start your agent by specifying the `GENESIS_URL` as `http://localhost:900/genesis` and see if/how that works?

**Comment by santidediego** [comment] 2021-06-04 14:09
Same error, I retrieve the genesis from `http://localhost:9000/genesis` but again 403 error code.

I can see from the logs that the agent is successfully bringing the genesis-url but again it does not connect to the ledger.

Any ideas?

**Comment by esune** [comment] 2021-06-04 16:43
Check this other issue, that seems lie it can potentially be related: https://github.com/hyperledger/aries-cloudagent-python/issues/1024

@andrewwhitehead @ianco is the `indy` wallet REQUIRED type when connecting to a ledger? If it is, this needs to be documented somewhere to avoid future issues.

**Comment by andrewwhitehead** [comment] 2021-06-04 16:45
Yes it is, currently.

**Comment by esune** [comment] 2021-06-04 16:50
Ha, thanks @andrewwhitehead 
Is there anywhere we could document this better (if it is not already documented) to prevent further issues? I admit I never think of that paramater and had to search the repo for other issues to come up with the answer I linked.

**Comment by swcurran** [comment] 2021-06-04 17:25
First place is to add it to the help text for the parameter -- maybe in CAPITALS :-).  Next might be to add a troubleshooting/FAQ page to the repo and add it there.  Not sure how many of those we have, but perhaps if we can make it easy to update.  Agree that the search on issues is not the easiest -- but that could be on the top of the Troubleshooting page, along with a request for people to add to the page.

**Comment by santidediego** [comment] 2021-06-07 14:42
Now it seems to work perfectly, even with a local Indy network. Definitely it was the provisioning. Thanks!
