### ISSUE TITLE
Issuer can't overwrite values in a credential proposal when sending credential offer and issuing credential based on a credential proposal

### ISSUE THREAD

**Issue by yunxi-zhang** [hyperledger/aries-cloudagent-python#1184] opened 2021-05-19 10:09 UTC
My issuer creates a credential schema that has below dummy attributes:
{"name", "badge", "date"}

A requester sends a credential proposal with below values to the issuer by calling this api: `/issue-credential-2.0/send-proposal`
```
{
 "name": "score",
 "value": "95"
 },
{
"name": "badge",
"value": ""
},
{
"name": "date",
"value": "18 May 2021"
}
```

When the issuer decides to add value to the "badge" attribute by calling its bond sending offer api: `issue-credential-2.0/records/{cred_ex_id}/send-offer`, which would look like below
```
{
 "name": "score",
 "value": "95"
 },
{
"name": "badge",
"value": "professional"
},
{
"name": "date",
"value": "18 May 2021"
}
```

The eventual issued credential's "badge" attribute still has no values as how it is proposed by the requester.

**Expected result**: the issuer should be able to overwrite the values in its issued credentials

**Comment by sklump** [comment] 2021-05-21 15:08
I can't reproduce it from current main:

Holder proposes:
![1-holder-send-proposal](https://user-images.githubusercontent.com/9336556/119158918-bb5dae80-ba24-11eb-926e-3be18bea54cf.png)

Issuer counters:
![2-issuer-counters-offer](https://user-images.githubusercontent.com/9336556/119158936-c0baf900-ba24-11eb-949c-c5905b42d760.png)

Holder requests, bound on credential exchange:
![3-holder-sends-bound-request](https://user-images.githubusercontent.com/9336556/119159023-d7615000-ba24-11eb-885f-3af97210e91d.png)

After issue, holder credential:
![4-holder-credential](https://user-images.githubusercontent.com/9336556/119159061-df20f480-ba24-11eb-8675-fbd9978a2200.png)

**Comment by yunxi-zhang** [comment] 2021-05-24 09:37
Hello @sklump, thanks for the response. Forgot to mention in my ticket, I enabled the **multi-tenancy** mode when trying this process. I just tried it again with the **multi-tenancy mode on**, and found out the issue might occur when the issuer tries to send a credential offer.

This is the record message when the issuer receives a credential proposal. I can see status is`proposal-received` in **line 174**. The cred_ex_id is `d57a1e3f-e721-45bf-b57b-db612bbdf089` in **line 171**
![image](https://user-images.githubusercontent.com/16185797/119326797-3370e200-bc7a-11eb-8294-1a38d48b3604.png)

Below shows a response message from the issuer when sending a bound credential offer using the same cred_ex_id `d57a1e3f-e721-45bf-b57b-db612bbdf089`
![image](https://user-images.githubusercontent.com/16185797/119327225-a712ef00-bc7a-11eb-8ec8-647735129803.png)

Input JSON payload. I haven't pasted the full attributes here as you see there is a comma in line 16, this is because there are sensitive information in other attributes.
![image](https://user-images.githubusercontent.com/16185797/119328146-b6466c80-bc7b-11eb-8829-6aedd077b3eb.png)

JSON response payload, you can see the value of the **badge** field has **no value** in **line 109**, and the status is "offer-sent" in **line 125**
![image](https://user-images.githubusercontent.com/16185797/119327408-dc1f4180-bc7a-11eb-9d49-63fd60f03abb.png)


![image](https://user-images.githubusercontent.com/16185797/119327452-e80b0380-bc7a-11eb-8f6e-8fe152e628c5.png)

Could you please try it again by turning on multi-tenancy mode and see if this could be reproduced? Thanks!

**Comment by yunxi-zhang** [comment] 2021-06-02 14:23
Hello @sklump, can you reproduce this issue. Am I the only one who got this issue?

**Comment by yunxi-zhang** [comment] 2021-06-02 14:29
Hello @swcurran , I see you put replied in another issue stating @sklump is no longer in the ACA-Py team. Could you find some one else to look at this issue, please? Thanks!

**Comment by swcurran** [comment] 2022-01-11 22:42
This one fell off the list.  I know you have a big deliverable completed @yunxi-zhang so I'm going to close this. Please reopen if appropriate.

**Closed by swcurran** 2022-01-11 22:42 UTC

**Comment by yunxi-zhang** [comment] 2022-01-12 20:16
@swcurran, this feature has not been implemented in my frontend demo, so suspect this issue might still exist. Will try it again when I retouch this feature in my frontend demo in due course.
