### ISSUE TITLE
Publish image action ARM support

### ISSUE THREAD

**Issue by andrej-zirko** [hyperledger/aries-cloudagent-python#2237] opened 2023-05-19 14:04 UTC
Although the release notes state that the images are now published for the linux/arm64 architecture as well, it appears that they are currently only available for linux/amd64.

https://github.com/hyperledger/aries-cloudagent-python/releases/tag/0.8.0-rc0

docker: Error response from daemon: image with reference ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.8.1 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.

https://github.com/hyperledger/aries-cloudagent-python/actions/runs/4630093197/jobs/8191197139
![image](https://github.com/hyperledger/aries-cloudagent-python/assets/7345510/570963d7-4b0b-45e3-9068-36d129f1b610)

**Comment by WadeBarnes** [comment] 2023-05-19 14:53
The related issue; https://github.com/hyperledger/aries-cloudagent-python/issues/2124

**Comment by swcurran** [comment] 2024-06-25 17:28
Closing this as duplicate of #2129

**Closed by swcurran** 2024-06-25 17:28 UTC
