### ISSUE TITLE
Unpacking and decorator check ordering

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-cloudagent-python#37] opened 2019-07-03 16:02 UTC
For context: https://github.com/hyperledger/aries-cloudagent-python/blob/727b3430492e3d3b9d96c8a648d792f673799058/aries_cloudagent/messaging/serializer.py#L51-L90

The order of decorator checks and unpacking seems off; it first deserializes which would result in a dictionary with 'tag' and 'iv' and 'ciphertext' etc for a packed message but then checks for '~thread' and '~transport' in that dictionary before unpacking the message.

Shouldn't it be unpacking the message before checking for decorators?

**Comment by swcurran** [comment] 2019-07-03 16:45
@nrempel - please take a look. Thanks.

**Comment by nrempel** [comment] 2019-07-03 17:43
This logic looks sound. I've tested this and it is working as intended with packed messages.

The code block referenced above handles plaintext messages.

If the message is packed it falls through to the following code-block which will be run when the message is packed:

https://github.com/hyperledger/aries-cloudagent-python/blob/727b3430492e3d3b9d96c8a648d792f673799058/aries_cloudagent/messaging/serializer.py#L72-L90

**Comment by WadeBarnes** [comment] 2019-07-03 17:53
I believe @sukalpomitra has an example of a deserialization error.

**Comment by dbluhm** [comment] 2019-07-03 17:55
https://github.com/hyperledger/aries-cloudagent-python/blob/727b3430492e3d3b9d96c8a648d792f673799058/aries_cloudagent/messaging/serializer.py#L88

For the decorator parsing to be run on messages that are packed, though, wouldn't the dictionary obtained at this line need to go through the processing above this block as well?

I don't have code myself; @sukalpomitra (rocket.chat handle) brought this to my attention. I'll see if he has code that can demonstrate this.

**Comment by nrempel** [comment] 2019-07-03 18:23
The processing still occurs, but it happens as part of a (de)serialization pipeline. You can see the decorators that are supported here:

https://github.com/hyperledger/aries-cloudagent-python/blob/727b3430492e3d3b9d96c8a648d792f673799058/aries_cloudagent/messaging/decorators/default.py#L12-L16

The prefix is applied here:

https://github.com/hyperledger/aries-cloudagent-python/blob/727b3430492e3d3b9d96c8a648d792f673799058/aries_cloudagent/messaging/decorators/base.py#L11

I believe in this case, `~transport` and `~thread` are extracted for plaintext messages early because they are needed in a special case.

@andrewwhitehead may have some insight there. I'm not sure what they are needed for prior to the usual de-serialization process.

I've been chatting with @sukalpomitra on Rocket Chat. I'm working on reproducing his issue but I'm not sure it's related.

**Comment by andrewwhitehead** [comment] 2019-07-03 18:27
The ~thread and ~transport parsing should move after the unpacking, they're both used in the return route handling.

**Comment by sukalpomitra** [comment] 2019-07-04 09:39
Hi All, I think we can close this defect. The actual defect was the byte array was coming as empty. But once it came in, it actually worked. So no change is required. Once the dictionary does not have the @type key, it goes to the routine where it gets unpacked.  @dbluhm please feel free to close the bug

**Comment by sklump** [comment] 2019-07-04 11:40
I'm not so sure about that. If a decorator is marked `required=True` in the schema class, this code strips it out before marshmallow validation and so no model instance can deserialize; marshmallow raises 'data not found' for it.

Aries#0036 is built on data structures with attachment decorators, so I've had to kludge around it like this in `aries_cloudagent/messaging/decorators/base.py:BaseDecoratorSet.`:
```
    def extract_decorators(self, message: Mapping, serialized=True) -> OrderedDict:
        """Extract decorators and return the remaining properties."""
        remain = OrderedDict()
        if message:
            pfx_len = len(self._prefix)
            for key, value in message.items():
                if key.startswith(self._prefix):
                    key = key[pfx_len:]
                    self.load_decorator(key, value, serialized)
                elif self._prefix in key:
                    field, key = key.split(self._prefix, 1)
                    self.field(field).load_decorator(key, value, serialized)
                    ### THE HORROR
                    if key == 'attach':
                        remain[f'{field}{self._prefix}{key}'] = value
                else:
                    remain[key] = value
        return remain
```
for the moment to get past it. Note that the attach decorator is part of my experimental branch, not yet in master.

**Comment by swcurran** [comment] 2019-07-15 21:36
@nrempel @andrewwhitehead - this is marked as Done, but the last comment does not shout "resolved" to me.  Can one/both of you please confirm that we are good and that the issue can be closed?

Thanks

**Comment by andrewwhitehead** [comment] 2019-07-15 21:37
@swcurran  Different issue, we can address that on the Aries 36 PR.

**Comment by sklump** [comment] 2019-07-15 22:26
It's resolved. One solution is to subclass the decorator set, inherit extract/load-decorators method, they pass that to the agent message+schema initializer in the AgentMessage subclass à la Aries#0036 PR.

**Closed** 2019-07-17 22:40 UTC
Labels: bug
