### ISSUE TITLE
Proof request and presentation: support arrays of credential requests and presentations?

### ISSUE THREAD

**Issue by docmanni** [hyperledger/aries-cloudagent-python#1072] opened 2021-04-07 16:59 UTC
I am thinking about two use cases:

1. immigration to a country: traveler needs to present his passport to the officer and, optionally, a visa and possibly multiple vaccination credentials. At the moment, attributes of different schemas can be requested in a list, but the whole presentation will fail if one credential is missing (e.g. not everyone requires a visa for entering a country). Thus, for travelers of different countries, multiple requests have to be sent: first, request passport, then request visa if required, then request vaccination credential A, then vaccination credential B etc. That takes a long time and requires too much interaction by the requesting side. It would be good to request an array of credentials at once, the presentation contains an array of matching credentials plus a separate field which lists the requests that could not be presented.

2. let's assume that health care information is stored as credentials (diagnosis/prescription records). I can't see any solution if a doctor wants to see a patient's records of the last 3 months. Proof presentations only show one credential, not an array of credentials which match the request, as far as I could find out so far.

Am I way off here? Or do I need to dig deeper and the things I want to achieve can actually be achieved with the current version of aca-py (0.6.0)? If so, some pointers into the right direction would be highly appreciated! (Still a noob in terms of aca-py... ;-) )

**Comment by sklump** [comment] 2021-04-08 15:05
1. Aca-py implements RFC 454 (https://github.com/hyperledger/aries-rfcs/tree/master/features/0454-present-proof-v2), which presents one proof. A protocol for a collection of presentations may be worth looking into, but it isn't 0454.

2. A credential is neither a certificate nor an attribute certificate. It is geared toward zero-knowledge proofs. Using credentials for non-zero-knowledge presentations is going to be kludgey by design.

**Comment by docmanni** [comment] 2021-04-08 15:21
>     1. Aca-py implements RFC 454 (https://github.com/hyperledger/aries-rfcs/tree/master/features/0454-present-proof-v2), which presents one proof. A protocol for a collection of presentations may be worth looking into, but it isn't 0454.

I understand. Would be a "nice to have", but can be done through the backdoor, I believe. A proof-request for the first credential (to stay in the example context of my original question: that could be the passport credential) could set a certain comment that a client can parse and then send proof presentation proposals one by one of requested credentials (visa, one or more vaccination credentials, ...). Certainly not what the inventors had in mind, I know, but a solution that could work. ;-)

>     2. A credential is neither a certificate nor an attribute certificate. It is geared toward zero-knowledge proofs. Using credentials for non-zero-knowledge presentations is going to be kludgey by design.

Yes, I was afraid of that. It is indeed an awkward design, need to think of a better way, possibly storing this stuff on Sawtooth or Fabric instead.

Thanks a lot for taking the time to answer my question! Much appreciated!

**Comment by sklump** [comment] 2021-04-08 15:22
In theory it could be possible to negotiate the shape of the proof via proposal/request back-and-forth. At present, this would be all manual with aca-py.

**Comment by swcurran** [comment] 2021-04-08 19:58
With both Indy AnonCreds and DIF Presentation Exchange, multiple proofs can be requested and sent in a single "normal" RFC 0454 Present Proof protocol execution.  It might be possible to handle the multiple vaccination credentials by having different restrictions (as defined in AnonCreds and DIF PE) used in the Proof Request.  Not an array, but an explicit request for several credentials.

It doesn't handle the general use case of an array of credentials where all are needed.  To get the UX right, you ideally only ask the the person once, and they acknowledge and send them all.  To properly handle that, something needs to be done via a protocol change -- either a change to an existing one, or a new one.  For example (this off the cuff), a new "send all credentials" protocol that notifies the holder that an array of proofs is being asked for, drops to a child RFC 0454 protocol instance with the Proof Request, and after completing the first instance with 0454, go back to the parent protocol instance and the holder sends the rest of the array of proofs, each as a message, with an "all done" message at the end.

**Comment by swcurran** [comment] 2022-01-11 22:32
Will be opening a new Issue to add support for Present Proof 1.1 which has support for this built in.  Closing this issue -- https://github.com/hyperledger/aries-rfcs/tree/main/features/0454-present-proof-v2#version-change-log

**Closed by swcurran** 2022-01-11 22:32 UTC
