### ISSUE TITLE
How to receive request events when connecting?  Thanks!

### ISSUE THREAD

**Issue by githubgood2020** [hyperledger/aries-cloudagent-python#1263] opened 2021-06-24 10:40 UTC
I installed ACA-PY agent locally, and then I started two instances of the agent to study the connection:
Agent for Faber: aca-py start --inbound-transport http localhost 8100 --outbound-transport http --endpoint http localhost 8101 --no-ledger --admin-insecure-mode --admin localhost 8102 --debug-connections
Agent for ALice: aca-py start --inbound-transport http localhost 8200 --outbound-transport http --endpoint http localhost 8201 --no-ledger --admin-insecure-mode --admin localhost 8202 --debug-connections

Then I followed the instructions of "Aries OpenAPI Demo": create invitation, receive invitation, accept invitation, then, in the next step "The Faber Agent Gets the Request", how to let Faber get the connection request? as the figure shows:
<img width="1026" alt="3-Faber-Connection-2" src="https://user-images.githubusercontent.com/65531227/123248702-ce2f3b80-d51a-11eb-839d-26271b34d1e8.png">

May anyone help my by telling me how to let Faber get the connection request, i.e., how to let Faber get the connection request event?
Thanks a lot!

**Comment by Fethbita** [comment] 2021-06-30 09:21
While creating invitation, do not leave an empty JSON body. To connect, the other agent needs to know the endpoint. So this:
```json
{
  "service_endpoint": "http://localhost:8100"
}
```
and after you receive invitation, before accepting it, you should write the Alice's endpoint in the endpoint box as such `http://localhost:8200` and now the Faber receives a connection request. Then when you are accepting request on Faber side, you should once more state your endpoint in the box `http://localhost:8100`. After this, if you send a basic message, the state will turn from `response` to `active`.

**Comment by santidediego** [comment] 2021-06-30 11:21
I am facing the same issue, in my case I´ve also put:
```
{
  "service_endpoint": "http://my_ip:8030"
}
```

I am getting in Faber´s console the following error, when calling: **POST /connections/receive-invitation** in Alice´s side

`aries_cloudagent.core.dispatcher ERROR Message parsing failed: Message does not contain '@type' parameter, sending problem report`

@Fethbita have you been able to solve your issue?

**Comment by Fethbita** [comment] 2021-06-30 11:40
@santidediego Can you paste in the invitation you are trying to receive here? Maybe a problem in JSON format?

**Comment by santidediego** [comment] 2021-06-30 12:09
Yes, here it is:
```
{
    "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0/invitation",
    "@id": "b2f8ab31-b5f0-4342-9dbc-79a811943664",
    "recipientKeys": [
      "AaTxZMVn8PhnpwD6XzQHNsrbwmeNJ2oKQ3sxoCPtpf6H"
    ],
    "label": "Aries Cloud Agent",
    "serviceEndpoint": "http://lab-indy-agent-0:8030"
  }
```
 I think the JSON is correct because I am getting a 200 code, but in Faber´s side I get the error message

**Comment by Fethbita** [comment] 2021-06-30 12:29
I actually can't reproduce your error on my side :/

**Comment by santidediego** [comment] 2021-06-30 12:55
It might be something related to endpoints. These are:

`http://lab-indy-agent-0:8030` and `http://lab-indy-agent-1:8030`, both passed it with --endpoint when starting both agents

Are you able to accept the invitation in the next step? Now I am getting, which might be useful for debugging:
```
No invitation found for pairwise connection in state invitation: a prior connection request may have updated the connection state
```

**Comment by Fethbita** [comment] 2021-06-30 14:14
I am indeed able to accept the invitation on the Alice side, while providing --endpoint, can you try `--endpoint http lab-indy-agent-0 8030`?

**Comment by santidediego** [comment] 2021-06-30 16:41
Done and nothing happens. Could be the inbound or outbound parameters? they are set as:
```
--inbound-transport [http, 0.0.0.0, 8030]
--outbound-transport http
```

**Comment by swcurran** [comment] 2022-01-11 22:59
Sorry we didn't get back to you on this.  Not sure what the issue is so am closing because of age.

**Closed by swcurran** 2022-01-11 22:59 UTC
