### ISSUE TITLE
seqNo null returned when creating schema

### ISSUE THREAD

**Issue by dnaicker** [hyperledger/aries-cloudagent-python#1401] opened 2021-09-08 08:28 UTC
when trying to create` credential id seqNo is null: "seqNo":null` returned from creating schema first and `credential id `can't be created and is returning  `error 400 schema does not exist`

post
> curl -X POST http://localhost:11000/schemas -H 'Content-Type: application/json' -d '{ "attributes": ["name", "age"], "schema_name": "my-schema", "schema_version": "1.0"}'

result
> {"schema_id": "PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0", "schema": {"ver": "1.0", "id": "PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0", "name": "my-schema", "version": "1.0", "attrNames": ["age", "name"], "seqNo": null}}

post
> curl -X POST http://localhost:11000/credential-definitions' -d '{"schema_id": "PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0", "tag": "default"}'

result
> 400: Ledger default has no schema PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0

**Comment by ianco** [comment] 2021-09-08 21:40
I'm not able to reproduce - I tested the above curl commands with a local instance of aca-py and von-network and was able to create the schema and cred def successfully.

@dnaicker can you provide more info about how you have your local environment setup?

**Comment by dnaicker** [comment] 2021-09-09 05:33
Hi @ianco 

My current setup is: Ubuntu 18 on Windows 10 with WSL2 and Docker 

I utilised the following steps to install pacakges and libraries for local setup:

> $ git clone https://github.com/hyperledger/aries-cloudagent-python
> $ cd aries-cloudagent-python
> $ pip3 install -r requirements.txt -r requirements.dev.txt -r requirements.indy.txt
> $ pip3 install --no-cache-dir -e .

> $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 68DB5E88
> $ sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic master"
> $ sudo apt-get update
> $ sudo apt-get install -y libindy

> sudo apt-get install jq
> install ngrok (download linux stable, unzip, add to bashrc path)

------------
start von-network (optional non-functional ledger pool not found) or connect to bcovrin (works but schema id seqNo: null)
> git clone https://github.com/bcgov/von-network.git
> cd von-network
> ./manage build (optional if not first time)
> ./manage start --logs  

> register DID for Issuer
> curl -X POST "http://dev.greenlight.bcovrin.vonx.io/register" \
> -d '{"seed": "Alice000000000000000000000000001", "role": "TRUST_ANCHOR", "alias": "Alice"}'

------------
startup issuer and holder agents

> aca-py start --label Alice -it http 0.0.0.0 8000 -ot http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --seed Alice000000000000000000000000001 --endpoint http://localhost:8000/ --debug-connections --auto-provision --wallet-name Alice1 --wallet-key secret --auto-accept-invites --auto-accept-requests --wallet-type indy

> aca-py start --label Bob -it http 0.0.0.0 8001 -ot http --admin 0.0.0.0 11001 --admin-insecure-mode --endpoint http://localhost:8001/ --genesis-url http://dev.greenlight.bcovrin.vonx.io/genesis --debug-connections --auto-provision --wallet-local-did --wallet-name Bob1 --wallet-key secret --auto-accept-invites --auto-accept-requests --wallet-type indy

------------
create did alice issuer

> curl -X POST "http://dev.greenlight.bcovrin.vonx.io/register" \
-d '{"seed": "Alice000000000000000000000000001", "role": "TRUST_ANCHOR", "alias": "Alice"}'

result
> {
  "did": "PLEVLDPJQMJvPLyX3LgB6S",
  "seed": "Alice000000000000000000000000001",
  "verkey": "DAwrZwgMwkTVHUQ8ZYAmuvzwprDmX8vFNXzFioxrWpCA"
}

------------
create invitation alice issuer
> curl -X POST "http://localhost:11000/out-of-band/create-invitation" \
   -H 'Content-Type: application/json' \
   -d '{
  "handshake_protocols": [
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"
  ],
  "use_public_did": false
}'

 result 
> {"invitation_url": "http://localhost:8000/?oob=eyJAdHlwZSI6ICJkaWQ6c292OkJ6Q2JzTlloTXJqSGlxWkRUVUFTSGc7c3BlYy9vdXQtb2YtYmFuZC8xLjAvaW52aXRhdGlvbiIsICJAaWQiOiAiY2RjN2QxMzUtMDQwMC00M2FjLWIyYTMtMzJiNjM5MzcxODUyIiwgImhhbmRzaGFrZV9wcm90b2NvbHMiOiBbImRpZDpzb3Y6QnpDYnNOWWhNcmpIaXFaRFRVQVNIZztzcGVjL2RpZGV4Y2hhbmdlLzEuMCJdLCAibGFiZWwiOiAiQWxpY2UiLCAic2VydmljZXMiOiBbeyJpZCI6ICIjaW5saW5lIiwgInR5cGUiOiAiZGlkLWNvbW11bmljYXRpb24iLCAicmVjaXBpZW50S2V5cyI6IFsiZGlkOmtleTp6Nk1rajQ1ZmJrQTlIaVN1NjlOaW1iQW95dGJwaHoxS3NrM3dBV2kxNW1jTXJDbmsiXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwOi8vbG9jYWxob3N0OjgwMDAvIn1dfQ==", "invi_msg_id": "cdc7d135-0400-43ac-b2a3-32b639371852", "invitation": {"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/out-of-band/1.0/invitation", "@id": "cdc7d135-0400-43ac-b2a3-32b639371852", "handshake_protocols": ["did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"], "label": "Alice", "services": [{"id": "#inline", "type": "did-communication", "recipientKeys": ["did:key:z6Mkj45fbkA9HiSu69NimbAoytbphz1Ksk3wAWi15mcMrCnk"], "serviceEndpoint": "http://localhost:8000/"}]}, "state": "initial", "trace": false}

------------
bob holder receives invitation
> curl -X POST "http://localhost:11001/out-of-band/receive-invitation" \
   -H 'Content-Type: application/json' \
   -d '{"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/out-of-band/1.0/invitation", "@id": "cdc7d135-0400-43ac-b2a3-32b639371852", "handshake_protocols": ["did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0"], "label": "Alice", "services": [{"id": "#inline", "type": "did-communication", "recipientKeys": ["did:key:z6Mkj45fbkA9HiSu69NimbAoytbphz1Ksk3wAWi15mcMrCnk"], "serviceEndpoint": "http://localhost:8000/"}]}'

result
> {"their_role": "inviter", "invitation_mode": "once", "accept": "auto", "updated_at": "2021-09-07 08:56:46.205894Z", "connection_id": "453eafbd-6655-4b3a-b82b-a505dc15a3f4", "their_label": "Alice", "created_at": "2021-09-07 08:56:46.198943Z", "my_did": "PA78aDUhvpncGscMrLLRt", "request_id": "bfe21704-4a70-4a17-8924-f2e3a6e2e117", "state": "request", "rfc23_state": "request-sent", "invitation_msg_id": "cdc7d135-0400-43ac-b2a3-32b639371852", "connection_protocol": "didexchange/1.0", "invitation_key": "5bpd1VuhxAxRyeY262Cy8o3ptQjUTroaUVo5FVeLvz1N", "routing_state": "none"}

------------
create schema

> curl -X POST http://localhost:11000/schemas -H 'Content-Type: application/json' -d '{ "attributes": ["name", "age"], "schema_name": "my-schema", "schema_version": "1.0"}'

result:
> {"schema_id": "PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0", "schema": {"ver": "1.0", "id": "PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0", "name": "my-schema", "version": "1.0", "attrNames": ["age", "name"], "seqNo": null}}

seqNo is null here

------------------
create credential definition
> curl -X POST http://localhost:11000/credential-definitions' -d '{"schema_id": "PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0", "tag": "default"}'

result:
> 400: Ledger default has no schema PLEVLDPJQMJvPLyX3LgB6S:2:my-schema:1.0

**Comment by ianco** [comment] 2021-09-09 15:43
Hi @dnaicker , thanks for all the details!

For the local scenario, I think you have a disconnect between running von-network in docker vs running all the aca-y agents locally.  Docker containers use an internal docker IP which is not visible to processes running on the local machine.

You can fix this easily by passing your local IP to von-network on startup, for example:

`./manage start 192.168.0.11 --logs`

You can see the IP address that the von-network nodes are running on via the genesis file - available at http://localhost:9000/genesis - this should be an IP visible to the agents.

(Alternately, if you run the agents using docker, via `./run_deme faber` for example, then they can connect to von-network using its default "docker" IP address)

Note - for the scenario where you're connecting to the bcovrin ledger, I'm not sure why you're getting an error, I'll try to reproduce.

**Comment by dnaicker** [comment] 2021-09-09 16:55
Thank you @ianco!

**Comment by dnaicker** [comment] 2021-09-10 05:37
Hi @ianco ,

I tried the above, and get a timeout ledger error with the following steps:

wifi address

> 192.168.8.105

von start
> ./manage start 192.168.8.105 --logs

------------
agents start
> aca-py start --label Alice -it http 0.0.0.0 8000 -ot http --admin 0.0.0.0 11000 --admin-insecure-mode --genesis-url http://192.168.8.105:9000/genesis --seed Alice000000000000000000000000001 --endpoint http://localhost:8000/ --debug-connections --auto-provision --wallet-name Alice1 --wallet-key secret --auto-accept-invites --auto-accept-requests --wallet-type indy

> aca-py start --label Bob -it http 0.0.0.0 8001 -ot http --admin 0.0.0.0 11001 --admin-insecure-mode --endpoint http://localhost:8001/ --genesis-url http://192.168.8.105:9000/genesis --debug-connections --auto-provision --wallet-local-did --wallet-name Bob1 --wallet-key secret --auto-accept-invites --auto-accept-requests --wallet-type indy

------------
genesis file on http://192.168.8.105:9000/genesis
> {"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"192.168.65.3","client_port":9702,"node_ip":"192.168.65.3","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node2","blskey":"37rAPpXVoxzKhz7d9gkUe52XuXryuLXoM6P6LbWDB7LSbG62Lsb33sfG7zqS8TK1MXwuCHj1FKNzVpsnafmqLG1vXN88rt38mNFs9TENzm4QHdBzsvCuoBnPH7rpYYDo9DZNJePaDvRvqJKByCabubJz3XXKbEeshzpz4Ma5QYpJqjk","blskey_pop":"Qr658mWZ2YC8JXGXwMDQTzuZCWF7NK9EwxphGmcBvCh6ybUuLxbG65nsX4JvD4SPNtkJ2w9ug1yLTj6fgmuDg41TgECXjLCij3RMsV8CwewBVgVN67wsA45DFWvqvLtu4rjNnE9JbdFTc1Z4WCPA3Xan44K1HoHAq9EVeaRYs8zoF5","client_ip":"192.168.65.3","client_port":9704,"node_ip":"192.168.65.3","node_port":9703,"services":["VALIDATOR"]},"dest":"8ECVSk179mjsjKRLWiQtssMLgp6EPhWXtaYyStWPSGAb"},"metadata":{"from":"EbP4aYNeTHL6q385GuVpRV"},"type":"0"},"txnMetadata":{"seqNo":2,"txnId":"1ac8aece2a18ced660fef8694b61aac3af08ba875ce3026a160acbc3a3af35fc"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node3","blskey":"3WFpdbg7C5cnLYZwFZevJqhubkFALBfCBBok15GdrKMUhUjGsk3jV6QKj6MZgEubF7oqCafxNdkm7eswgA4sdKTRc82tLGzZBd6vNqU8dupzup6uYUf32KTHTPQbuUM8Yk4QFXjEf2Usu2TJcNkdgpyeUSX42u5LqdDDpNSWUK5deC5","blskey_pop":"QwDeb2CkNSx6r8QC8vGQK3GRv7Yndn84TGNijX8YXHPiagXajyfTjoR87rXUu4G4QLk2cF8NNyqWiYMus1623dELWwx57rLCFqGh7N4ZRbGDRP4fnVcaKg1BcUxQ866Ven4gw8y4N56S5HzxXNBZtLYmhGHvDtk6PFkFwCvxYrNYjh","client_ip":"192.168.65.3","client_port":9706,"node_ip":"192.168.65.3","node_port":9705,"services":["VALIDATOR"]},"dest":"DKVxG2fXXTU8yT5N7hGEbXB3dfdAnYv1JczDUHpmDxya"},"metadata":{"from":"4cU41vWW82ArfxJxHkzXPG"},"type":"0"},"txnMetadata":{"seqNo":3,"txnId":"7e9f355dffa78ed24668f0e0e369fd8c224076571c51e2ea8be5f26479edebe4"},"ver":"1"}
{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node4","blskey":"2zN3bHM1m4rLz54MJHYSwvqzPchYp8jkHswveCLAEJVcX6Mm1wHQD1SkPYMzUDTZvWvhuE6VNAkK3KxVeEmsanSmvjVkReDeBEMxeDaayjcZjFGPydyey1qxBHmTvAnBKoPydvuTAqx5f7YNNRAdeLmUi99gERUU7TD8KfAa6MpQ9bw","blskey_pop":"RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP","client_ip":"192.168.65.3","client_port":9708,"node_ip":"192.168.65.3","node_port":9707,"services":["VALIDATOR"]},"dest":"4PS3EDQ3dW1tci1Bp6543CfuuebjFrg36kLAUcskGfaA"},"metadata":{"from":"TWwCRQRZ2ZHMJFn9TzLp7W"},"type":"0"},"txnMetadata":{"seqNo":4,"txnId":"aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008"},"ver":"1"}

----------------
Wireless LAN adapter WiFi:
> Connection-specific DNS Suffix  . : localhost
Link-local IPv6 Address . . . . . : fe80::c110:9766:806b:8b9e%11
IPv4 Address. . . . . . . . . . . : 192.168.8.105
Subnet Mask . . . . . . . . . . . : 255.255.255.0
Default Gateway . . . . . . . . . : fe80::1%11
                                   192.168.8.100
---------------------------
The error I get:
> Traceback (most recent call last):
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/utils/http.py", line 106, in fetch
    response: ClientResponse = await session.get(url, headers=headers)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/client.py", line 521, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 1032, in _create_direct_connection
    client_error=client_error,
  File "/home/denver/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
concurrent.futures._base.CancelledError

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/utils/http.py", line 112, in fetch
    return await (response.json() if json else response.text())
  File "/home/denver/.local/lib/python3.6/site-packages/async_timeout/__init__.py", line 55, in __aexit__
    self._do_exit(exc_type)
  File "/home/denver/.local/lib/python3.6/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/config/ledger.py", line 32, in fetch_genesis_transactions
    return await fetch(genesis_url, headers=headers)
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/utils/http.py", line 115, in fetch
    raise FetchError("Exceeded maximum fetch attempts") from e
aries_cloudagent.utils.http.FetchError: Exceeded maximum fetch attempts

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/core/conductor.py", line 93, in setup
    await get_genesis_transactions(context.settings)
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/config/ledger.py", line 43, in get_genesis_transactions
    txns = await fetch_genesis_transactions(settings["ledger.genesis_url"])
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/config/ledger.py", line 34, in fetch_genesis_transactions
    raise ConfigError("Error retrieving ledger genesis transactions") from e
aries_cloudagent.config.base.ConfigError: Error retrieving ledger genesis transactions

> Shutting down
2021-09-10 07:12:19,422 asyncio ERROR Task exception was never retrieved
future: <Task finished coro=<run_loop.<locals>.done() done, defined at /mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/commands/start.py:77> exception=AttributeError("'NoneType' object has no attribute 'context'",)>
Traceback (most recent call last):
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/commands/start.py", line 79, in done
    await shutdown
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/commands/start.py", line 35, in shutdown_app
    await conductor.stop()
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/core/conductor.py", line 355, in stop
    multitenant_mgr = self.context.inject_or(BaseMultitenantManager)
  File "/mnt/c/Users/denai/Github/aries-cloudagent-python/aries_cloudagent/core/conductor.py", line 85, in context
    return self.root_profile.context
AttributeError: 'NoneType' object has no attribute 'context'

I am able to view the genesis file if I navigate to http://192.168.8.105:9000/genesis

-----------
if i do a register seed call to http://192.168.8.105:9000/register, a timeout occurs: 

> curl -X POST "http://localhost:9000/register" -d '{"seed": "Alice000000000000000000000000001", "role": "TRUST_ANCHOR", "alias": "Alice"}'

result
> curl: (7) Failed to connect to 192.168.8.105 port 9000: Connection timed out

-----------
if i change the ip to client or node ip from the genesis file and run a register, I get a timeout as well

> curl -X POST "http://192.168.65.3:9701/register" -d '{"seed": "Alice000000000000000000000000001", "role": "TRUST_ANCHOR", "alias": "Alice"}'

**Comment by ianco** [comment] 2021-09-10 13:45
Hi @dnaicker , sorry I'm not sure what is happening.  The IP in your genesis file is "192.168.65.3" even though you start with a different IP ("192.168.8.105")

The timeouts/connection errors are due to this IP mismatch, but I'm not sure what's causing it.

**Comment by dnaicker** [comment] 2021-09-10 15:00
@ianco is there a full proof instructions that i could follow to get a ledger running? i have tried https://github.com/hyperledger/aries-acapy-controllers/blob/main/AliceFaberAcmeDemo/README.md

i tried akiff manji aca-py controllers repo and the ledger and examples work flawlessly: https://github.com/hyperledger/aries-acapy-controllers/blob/main/AliceFaberAcmeDemo/README.md, i am trying to see how he is doing it

**Comment by ianco** [comment] 2021-09-10 16:10
Hi @dnaicker all the aca-py demo's have been tested, both with a local von-network as well as a remote ledger (such as the bcorvin ledgers).  @amanji 's controller demo's use the same underlying aca-py agent so if they are working then the aca-py demo's should work as well.

It looks like you are getting errors running a local ledger, so I suggest to focus on getting the demo's working using `LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io` (like Akiff's demo's)

**Comment by dnaicker** [comment] 2021-09-10 17:00
@ianco i am using bcovrin but the seqNo:null response is blocking me from completing the creation of schema credential id and then doing the issue credential steps, which is why i wanted to get the local ledger working so that i could somehow overcome that error

...with akiff the entire demo runs perfectly, i looked at the script and its referencing a lot of global vars which i cant find and ip port addresses seem to be the usual, not sure how to extract a specific command that could assis

the aca-py controllers work its just the indy ledger port connectivity without akiffs demo script

**Comment by ianco** [comment] 2021-09-10 17:29
Hi @dnaicker I'm not able to reproduce the `seqNo:null` error, I'm able to run `LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber` and then create schemas and cred defs with no issues.

**Comment by dnaicker** [comment] 2021-09-10 17:32
thanks @ianco will try again

**Comment by swcurran** [comment] 2022-01-12 01:03
Closing

**Closed by swcurran** 2022-01-12 01:03 UTC
