### ISSUE TITLE
Trouble Running Faber Demo On Apple Silicon

### ISSUE THREAD

**Issue by drewcapener** [hyperledger/aries-cloudagent-python#1689] opened 2022-03-24 20:28 UTC
Hey, I am an Aries newbie, and I am just getting familiar with some of the projects. I wanted to run the [Alice/Faber Demo](https://github.com/hyperledger/aries-cloudagent-python/blob/main/demo/README.md) according to the instructions provided under the "Running in Docker" section. I was able to successfully follow the instructions up until `./run_demo faber` where I get the following error: 

`Faber      | Operation not permitted (src/thread.cpp:231)`
`Faber      | qemu: uncaught target signal 6 (Aborted) - core dumped`

As mentioned in the title, I am on Apple Silicon, and my instinct is to say this is where the issue is coming from because I have seen people getting this error on m1 chips [elsewhere](https://gitlab.com/qemu-project/qemu/-/issues/340), but this could also be something else. I would be very grateful to anyone who could help me figure this out!

**Comment by andrewwhitehead** [comment] 2022-03-24 21:20
Hiya, could you please add the versions of your MacOS install and Docker install for reproduction. Are you using Docker Desktop?

**Comment by drewcapener** [comment] 2022-03-24 21:45
@andrewwhitehead Thanks for the help.

Monterey 12.2.1
Docker Desktop 20.10.11

**Comment by drewcapener** [comment] 2022-03-25 19:27
[This issue](https://github.com/bcgov/von-network/issues/182) feels like it might hold some answers?

**Comment by drewcapener** [comment] 2022-03-25 19:30
@TimoGlastra I saw you were wrestling with this issue on a couple of issues. Did you get it figured out?

**Comment by drewcapener** [comment] 2022-03-25 20:01
Bit of an update- I was able to replace the base image with an unofficial one (snel/von-image:py36-1.16-arm64) built for arm64. I'm not sure if this will work, but for now it seems to have at least moved me to a different issue. Now, I'm getting the following: 

`#8 16.77 ERROR: Could not find a version that satisfies the requirement aries-askar~=0.2.4 (from versions: 0.1.0, 0.1.2)`

**Comment by andrewwhitehead** [comment] 2022-03-25 21:42
It has universal packages for Askar, maybe you need to upgrade pip?

**Comment by drewcapener** [comment] 2022-03-25 22:13
@andrewwhitehead Just to make sure we're on the same page, are you suggesting upgrading pip in the container? I tried adding this line to no avail:

`RUN pip3 install --upgrade pip`

and then tried this one with no success either:

`RUN python3 -m pip install --upgrade pip`

**Comment by andrewwhitehead** [comment] 2022-03-25 22:20
Actually I suppose you're running a Linux arm64 environment in this case, so there isn't a published package for that yet.

**Comment by drewcapener** [comment] 2022-03-25 22:26
@andrewwhitehead What's the likelihood of getting something like that done? I'm unfamiliar with the process of publishing python packages. Is it something I could help facilitate in some way? Or should I try to build Askar for Linux arm64 just for my own purposes and try to replace the dependency?

**Comment by andrewwhitehead** [comment] 2022-03-25 22:34
It's the same issue for indy-credx and for indy-vdr, so it might take a while to get the build process sorted out for those. You could build and package each of those within a similar docker container. I filed an issue for Askar to test out Zig for cross compilation: https://github.com/hyperledger/aries-askar/issues/42

**Comment by drewcapener** [comment] 2022-03-25 22:41
Alright, thanks for filing that issue. I'll see if I can do those builds and get it working that way in the meantime. Happy to help facilitate the cross compilation for those who come up behind us if there's anything I can do on that front.

**Comment by TimoGlastra** [comment] 2022-03-26 12:02
Can't be of much help here sadly.

I run ACA-Py directly on my computer (no docker), and for places where I need to use ACA-Py with docker I use a digital ocean droplet that I develop on. It's not ideal, but spent way too much time getting things to work that just works on other (non-M1) machines 😅

Maybe you can use the snel/von-image with indy-sdk instead of askar? Not sure if that would work...

**Comment by etschelp** [comment] 2022-04-21 08:22
The issue is the qemu update introduced with docker desktop 4.1.0 if you downgrade to 4.0.1 you can run aca-py images emulated. This is not ideal, but might serve as a workaround until there is an image for arm64.

**Comment by swcurran** [comment] 2022-06-03 19:33
It would be great if someone could add a document or add a section in the developer readme about how to run on M1 hardware -- documenting whatever the current state is.

That said, I'm going to close this one. Feel free to reopen or create a new one requesting M1 guidance.

**Closed by swcurran** 2022-06-03 19:33 UTC
