### ISSUE TITLE
Able to recreate the same schema

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-cloudagent-python#1661] opened 2022-03-10 10:50 UTC
We have recently updated our ckoudagent to version 0.7.3 and I found out that we can register, or at least create, a schema multiple times with the exact same values. 

To reproduce:

_exectute multiple times_
```sh
curl -X POST $AGENT_ENDPOINT -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"attributes\": [ \"score\" ], \"schema_name\": \"prefs\", \"schema_version\": \"1.0\"}"
```

```sh
curl -X GET $AGENT_ENDPOINT -H "accept: application/json"
```

reponse should contain multiple of the same schema like this:

```json
{
  "schema_ids": [
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test2:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test2:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:prefs:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test2:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test2:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test2:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:prefs:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test-demo:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0",
    "Ehx3RZSV38pn3MYvxtHhbQ:2:test:1.0"
  ]
}
```

I believe it was checked before if the schema already exists. When it exists it will not be created but just returned what it found. And if it does not exist it would register it and return the schema. Is this a bug or something that changed that I am not aware of?

**Comment by swcurran** [comment] 2022-03-10 12:22
I think that is expected behaviour.  Whenever you start an agent you want to be sure that the ledger objects exist in the wallet and ledger, in case this is the first instance of the agent. So you check to see if the needed objects existing in both places, creating them if necessary and (again, I think) caching them if not.

@ianco -- do I have that right?

**Comment by swcurran** [comment] 2022-03-10 16:55
It depends what's happening behind the scenes. You should be able to call the admin endpoint multiple times and get an answer back that it is published everytime.  Each time you call, there should be a check the object is in the wallet (and create it if not) and that the object is on the ledger (and create it if not).  So calling it many times should result in the same behaviour, even if there is no change to the wallet and/or ledger because the object already exists.

**Comment by ianco** [comment] 2022-03-10 16:55
I'd need to check to be sure.  I know there's a check on the cred def, because if you re-create a cred def you can wind up with different signing info in your wallet vs on the ledger.  I'm not sure offhand what checks are in place for creating schemas.

**Comment by ianco** [comment] 2022-03-10 16:58
... just taking a quick look in the code I don't see any checks when creating a schema, whether the schema already exists

**Comment by ianco** [comment] 2022-03-10 17:00
.... and just running a quick test with faber, if you create the same schema multiple times, you wind up with multiple records in the wallet, but the schema is only created once on the ledger

**Comment by TimoGlastra** [comment] 2022-03-10 17:04
To add, we thought this was different in 0.6.0, but after doing a quick check the same behaviour is present in 0.6.0.

Doesn't mean the behaviour is justified, just that it's always been this way, contrary to what the initial issue described

**Comment by swcurran** [comment] 2022-03-10 17:17
Ok…agree the code is wrong as it exists today. Volunteer to fix?

**Comment by blu3beri** [comment] 2022-03-11 10:18
I can give it a go!

**Comment by swcurran** [comment] 2022-06-03 19:48
Any update on this?  I know there was some work on duplicate schemas #1786 -- did that address this issue?

I'm going to assume that it did and close this. If someone can take a look at this and it's not fixed, please reopen.

**Closed by swcurran** 2022-06-03 19:48 UTC
